version: "3.9"

services:
  karoseri360_grpc:
    image: paruliano/karoseri360_grpc:v1.0.4
    environment:
      HTTP_HOST: ${HTTP_HOST}
      GRPC_HOST: ${GRPC_HOST}
      DB_DEBUG: "true"
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_NAME: ${MYSQL_DATABASE}
      MYSQL_URL: "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/${MYSQL_DATABASE}?charset=utf8mb4&parseTime=True&loc=UTC"
      REDIS_HOST: "redis:6379"
    ports:
      - "7000:7000"
      - "7001:7001"
    depends_on:
      - mysql
      - redis
      - nsqlookupd
      - nsqd

  karoseri360_fe:
    image: paruliano/karoseri360_fe:v1.0.4
    environment:
      PORT: "7090"
      GRPC_ENDPOINT: ${GRPC_ENDPOINT}
      DB_HOST: ${DB_HOST}
      DB_PORT: "3306"
      DB_USER: ${DB_HOST}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_BACKUP_DIR: "backups"
      SESSION_SECRET: "9943kmfsdgdmgdjkik93493ujjfgdkgdkgkgkdgk535"
    ports:
      - "7090:7090"
    depends_on:
      - karoseri360_grpc
      - mysql
      - redis
      - nsqlookupd
      - nsqd

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nsqlookupd:
    image: nsqio/nsq:latest
    command: ["/nsqlookupd"]
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq:latest
    command: ["/nsqd", "--lookupd-tcp-address=nsqlookupd:4160"]
    ports:
      - "4150:4150"
      - "4151:4151"
    depends_on:
      - nsqlookupd

  nsqadmin:
    image: nsqio/nsq:latest
    command: ["/nsqadmin", "--lookupd-http-address=nsqlookupd:4161"]
    ports:
      - "4171:4171"
    depends_on:
      - nsqlookupd

volumes:
  mysql_data:
